<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType> <!-- WinExe, чтобы консоль не висела на фоне -->
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms> <!-- Включаем WinForms -->
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OpcNetApi">
      <HintPath>libs\OpcNetApi.dll</HintPath>
    </Reference>
    <Reference Include="OpcNetApi.Com">
      <HintPath>libs\OpcNetApi.Com.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
